"""
make_figures_and_tables.py
---------------------------
Aggregates the outputs of evaluate.py (eval_result.json) and train.py
(training_log.csv) across methods into the exact assets you need for the
report: the main results table (paper's Table 2), a qualitative prompt
comparison table (Table 4), training curves (Figure 1: task-reward proxy
ASR & PPL vs. epoch), and a t-SNE diversity plot (Figure 3).

Usage example:
  python src/make_figures_and_tables.py \\
      --run outputs/rlta:RLTA \\
      --run outputs/rlta_pp:"RLTA++ (ours)" \\
      --run outputs/ablation_no_rsem:"w/o Rsem" \\
      --run outputs/ablation_no_rdiv:"w/o Rdiv" \\
      --pair_result outputs/pair_baseline/eval_result.json \\
      --out_dir outputs/report_assets
"""

import argparse
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def parse_runs(run_args):
    runs = []
    for r in run_args:
        if ":" in r:
            path, tag = r.split(":", 1)
        else:
            path, tag = r, Path(r).name
        runs.append((Path(path), tag))
    return runs


def fmt(x, nd=3):
    return "-" if x is None else f"{x:.{nd}f}"


def build_main_results_table(runs, pair_result_path, out_dir):
    rows = []
    for run_dir, tag in runs:
        eval_path = run_dir / "eval_result.json"
        if not eval_path.exists():
            print(f"[warn] No eval_result.json in {run_dir}, skipping. Run evaluate.py first.")
            continue
        with open(eval_path) as f:
            r = json.load(f)
        rows.append({"Method": tag, "ASR": r["ASR"], "BS-F1": r["BS_F1"], "Div-4": r["Div_4"], "PPL": r["PPL"]})

    if pair_result_path and Path(pair_result_path).exists():
        with open(pair_result_path) as f:
            r = json.load(f)
        rows.insert(0, {"Method": "PAIR", "ASR": r["ASR"], "BS-F1": r.get("BS_F1"),
                         "Div-4": r.get("Div_4"), "PPL": r.get("PPL")})

    df = pd.DataFrame(rows)
    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_dir / "table2_main_results.csv", index=False)

    md_lines = ["| Method | ASR ↑ | BS-F1 ↑ | Div-4 ↑ | PPL ↓ |", "|---|---|---|---|---|"]
    for row in rows:
        md_lines.append(
            f"| {row['Method']} | {fmt(row['ASR'])} | {fmt(row['BS-F1'])} | "
            f"{fmt(row['Div-4'])} | {fmt(row['PPL'], 1)} |"
        )
    (out_dir / "table2_main_results.md").write_text("\n".join(md_lines), encoding="utf-8")
    print(f"[tables] Table 2 (main results) -> {out_dir / 'table2_main_results.csv'} / .md")
    return df


def build_qualitative_table(runs, out_dir, n_examples=5):
    """Table 4: same test-set target strings, prompts generated by each method."""
    per_method_examples = {}
    for run_dir, tag in runs:
        eval_path = run_dir / "eval_result.json"
        if not eval_path.exists():
            continue
        with open(eval_path) as f:
            r = json.load(f)
        per_method_examples[tag] = {e["target"]: e for e in r["per_example"]}

    if not per_method_examples:
        print("[tables] No eval results found for qualitative table, skipping.")
        return

    all_targets = list(next(iter(per_method_examples.values())).keys())[:n_examples]
    rows = []
    for t in all_targets:
        row = {"Target": t}
        for tag, examples in per_method_examples.items():
            ex = examples.get(t)
            row[f"{tag} prompt"] = ex["generated_prompt"] if ex else "-"
        rows.append(row)

    df = pd.DataFrame(rows)
    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_dir / "table4_qualitative_comparison.csv", index=False)
    print(f"[tables] Table 4 (qualitative comparison) -> {out_dir / 'table4_qualitative_comparison.csv'}")


def plot_training_curves(runs, out_dir):
    """Figure 1: per-epoch mean diagnostic ASR and mean PPL, across methods
    (uses the diag_bleu/diag_ppl columns logged by train.py for EVERY
    method, so this is a fair comparison regardless of which reward each
    variant actually optimizes)."""
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))

    for run_dir, tag in runs:
        log_path = run_dir / "logs" / "training_log.csv"
        if not log_path.exists():
            print(f"[figures] No training_log.csv in {run_dir}, skipping curve for {tag}.")
            continue
        df = pd.read_csv(log_path)
        if df.empty:
            continue
        per_epoch = df.groupby("epoch").agg(
            mean_diag_asr=("mean_diag_asr", "mean"),
            mean_ppl=("mean_ppl", "mean"),
        ).reset_index()

        linestyle = "-" if "++" in tag or "ours" in tag.lower() else "--"
        axes[0].plot(per_epoch["epoch"], per_epoch["mean_diag_asr"], linestyle, marker="o", label=tag)
        axes[1].plot(per_epoch["epoch"], per_epoch["mean_ppl"], linestyle, marker="o", label=tag)

    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Diagnostic ASR (BLEU ≥ 0.5) on training batches")
    axes[0].set_title("ASR vs. epoch")
    axes[0].legend()

    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Mean prompt perplexity (under reference policy)")
    axes[1].set_title("Prompt PPL vs. epoch")
    axes[1].legend()

    fig.suptitle("Figure 1: Training curves (RLTA dashed, RLTA++ solid)")
    fig.tight_layout()
    out_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_dir / "figure1_training_curves.png", dpi=150)
    plt.close(fig)
    print(f"[figures] Figure 1 (training curves) -> {out_dir / 'figure1_training_curves.png'}")


def plot_tsne(runs, out_dir, perplexity=5):
    """Figure 3: t-SNE of test-set prompt embeddings for each method."""
    from sklearn.manifold import TSNE

    all_embeddings, all_tags = [], []
    for run_dir, tag in runs:
        eval_path = run_dir / "eval_result.json"
        if not eval_path.exists():
            continue
        with open(eval_path) as f:
            r = json.load(f)
        embs = r.get("embeddings")
        if not embs:
            continue
        all_embeddings.extend(embs)
        all_tags.extend([tag] * len(embs))

    if len(all_embeddings) < 4:
        print("[figures] Not enough embeddings across runs for a meaningful t-SNE plot "
              "(need >= 4 total; this is expected on the tiny smoke-test data). Skipping.")
        return

    X = np.array(all_embeddings)
    n_samples = X.shape[0]
    safe_perplexity = max(2, min(perplexity, (n_samples - 1) // 3))
    tsne = TSNE(n_components=2, perplexity=safe_perplexity, random_state=42, init="pca")
    coords = tsne.fit_transform(X)

    fig, ax = plt.subplots(figsize=(6, 5))
    unique_tags = sorted(set(all_tags))
    for tag in unique_tags:
        idx = [i for i, t in enumerate(all_tags) if t == tag]
        ax.scatter(coords[idx, 0], coords[idx, 1], label=tag, alpha=0.7)
    ax.set_title("Figure 3: t-SNE of test-set jailbreaking prompt embeddings")
    ax.legend()
    fig.tight_layout()
    out_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_dir / "figure3_tsne_diversity.png", dpi=150)
    plt.close(fig)
    print(f"[figures] Figure 3 (t-SNE diversity) -> {out_dir / 'figure3_tsne_diversity.png'}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--run", action="append", required=True,
                    help="path:tag, e.g. outputs/rlta_pp:'RLTA++ (ours)'. Repeatable.")
    p.add_argument("--pair_result", default=None)
    p.add_argument("--out_dir", default="outputs/report_assets")
    args = p.parse_args()

    runs = parse_runs(args.run)
    out_dir = Path(args.out_dir)

    build_main_results_table(runs, args.pair_result, out_dir)
    build_qualitative_table(runs, out_dir)
    plot_training_curves(runs, out_dir)
    plot_tsne(runs, out_dir)

    print(f"\n[done] All report assets written to {out_dir}")


if __name__ == "__main__":
    main()
